# Generated by Django 4.2.7 on 2023-11-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('PRICE', models.CharField(max_length=2083)),
                ('image_url', models.CharField(max_length=2083)),
            ],
        ),
    ]
