# Generated by Django 4.2.7 on 2023-11-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRICE',
            field=models.CharField(default=1, max_length=2083),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
