# Generated by Django 4.2.7 on 2023-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_offer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, max_length=2083, upload_to=''),
            preserve_default=False,
        ),
    ]
