# Generated by Django 4.2.7 on 2023-11-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='PRICE',
            new_name='stem',
        ),
    ]
