# Generated by Django 4.2.7 on 2023-11-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_price_product_stem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='PRICE',
            new_name='stem',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='stock',
        ),
    ]
