# Generated by Django 4.2.7 on 2023-11-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_price_cart_stem_remove_cart_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=1, max_length=2083, upload_to=''),
            preserve_default=False,
        ),
    ]
