# Generated by Django 4.2.7 on 2023-11-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_cart_image_url_cart_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='stock',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='new',
            old_name='PRICE',
            new_name='stem',
        ),
        migrations.RemoveField(
            model_name='new',
            name='image_url',
        ),
        migrations.AddField(
            model_name='new',
            name='image',
            field=models.ImageField(default=1, max_length=2083, upload_to=''),
            preserve_default=False,
        ),
    ]
