# Generated by Django 4.2.7 on 2024-03-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_rename_stock_new_answer_rename_price_new_stem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="exercise_images/")),
            ],
        ),
    ]
